channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - contourpy=1.3.2=py310h3788b33_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - fonttools=4.59.2=py310h3406613_0
  - freetype=2.14.0=ha770c72_1
  - kiwisolver=1.4.9=py310haaf941d_1
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1423503_1
  - lerc=4.0.0=h0aef613_1
  - libblas=3.9.0=35_h4a7cf45_openblas
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcblas=3.9.0=35_h0358290_openblas
  - libdeflate=1.24=h86f0d12_0
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.14.0=ha770c72_1
  - libfreetype6=2.14.0=h73754d4_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgfortran=15.1.0=h69a702a_5
  - libgfortran5=15.1.0=hcea5267_5
  - libgomp=15.1.0=h767d61c_4
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=35_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libpng=1.6.50=h421ea60_1
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-ng=15.1.0=h4852527_4
  - libtiff=4.7.0=h8261f1e_6
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-base=3.10.6=py310hfde16b3_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - numpy=2.2.6=py310hefbff90_0
  - openjpeg=2.5.3=h55fea9a_1
  - openssl=3.5.2=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.2=py310h0158d43_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pillow=11.3.0=py310hb7da693_1
  - pip=25.2=pyh8b19718_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - python=3.10.18=hd6af730_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h434a139_5
  - readline=8.2=h8c095d6_2
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - statsmodels=0.14.5=py310haaf2d95_0
  - tk=8.6.13=noxft_hd72426e_102
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py310h7c4b9e2_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - anndata==0.11.4
      - array-api-compat==1.12.0
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - comm==0.2.3
      - debugpy==1.8.16
      - decorator==5.2.1
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - faiss-cpu==1.7.4
      - fastcluster==1.3.0
      - filelock==3.19.1
      - frozenlist==1.8.0
      - fsspec==2025.7.0
      - h5py==3.14.0
      - hf-xet==1.1.10
      - huggingface-hub==0.35.3
      - idna==3.11
      - igraph==0.11.9
      - ipykernel==6.30.1
      - ipython==8.37.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - legacy-api-wrap==1.4.1
      - lightning==2.5.5
      - lightning-utilities==0.15.2
      - llvmlite==0.44.0
      - markupsafe==3.0.2
      - matplotlib-inline==0.1.7
      - modin==0.35.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - natsort==8.4.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - novae==1.0.0
      - numba==0.61.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - parso==0.8.5
      - pexpect==4.9.0
      - platformdirs==4.4.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pynndescent==0.5.13
      - pynvml==13.0.1
      - pyparsing==3.2.3
      - pytorch-lightning==2.5.5
      - pyyaml==6.0.3
      - pyzmq==27.0.2
      - requests==2.32.5
      - safetensors==0.6.2
      - scanpy==1.11.4
      - scikit-learn==1.7.1
      - scipy==1.15.3
      - session-info2==0.2.1
      - stack-data==0.6.3
      - sympy==1.14.0
      - termcolor==3.1.0
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - torch==2.8.0
      - torch-geometric==2.7.0
      - torchmetrics==1.8.2
      - torchvision==0.23.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==3.4.0
      - typing-extensions==4.15.0
      - umap-learn==0.5.9.post2
      - urllib3==2.5.0
      - wcwidth==0.2.13
      - xxhash==3.6.0
      - yarl==1.22.0
